name: Build Release

on: 
  workflow_dispatch:

jobs:
  build_holylib:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "holylib"
      BUILD_64x: "true"
      REALM: "sv"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "false"
      ARTIFACT_EXPIRE: "1"
      ADDITIONAL_DATA: "1"

  build_ghostinj:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_PATH: "ghostinj-dll/"
      PROJECT_NAME: "ghostinj"
      BUILD_64x: "true"
      LINUX_FILEEXTENTION: "dll"
      BUILD_WINDOWS: "false"
      USE_PREFIX: "false"
      ARTIFACT_EXPIRE: "1"
      ADDITIONAL_DATA: "1"