name: Build Plugin

on: 
  push:
    paths:
      - '.github/workflows/compile.yml'
      - 'source/**'
      - 'gluatests/**'
      - 'libs/**'
      - 'premake5.lua'
      - '!source/public/README.md'
  pull_request:
  workflow_dispatch:

jobs:
  build_plugin_windows:
    name: "Build Plugin"
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "holylib"
      BUILD_64x: "true"
      REALM: "sv"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "true"
      BUILD_LINUX: "false"
      ARTIFACT_EXPIRE: "7"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-7"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-3"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
      BUILD_CACHE: "true"

  build_plugin_linux:
    name: "Build Plugin"
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "holylib"
      BUILD_64x: "true"
      REALM: "sv"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "false"
      ARTIFACT_EXPIRE: "7"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-7"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-3"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
      BUILD_CACHE: "true"

  build_testingarea:
    name: "Build 32x (Testing Area - Dev)"
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    secrets:
      PTERODACTYL_KEY: ${{ secrets.PTERODACTYL_KEY }}
      PTERODACTYL_SERVER: ${{ secrets.PTERODACTYL_SERVER }}
      PTERODACTYL_URL: ${{ secrets.PTERODACTYL_URL }}
    with:
      PROJECT_NAME: "holylib"
      BUILD_64x: "false"
      REALM: "sv"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "false"
      UPLOAD: "pterodactyl"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-7"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-3"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
      PTERODACTYL_RESTART_SLEEPTIME: "0"
      PTERODACTYL_RESTART: "true"
      BUILD_CACHE: "true"

  build_testingarea_dev2: # Could make this use the already created artifact but I'm too lazy rn
    name: "Build 32x (Testing Area - Dev2)"
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    secrets:
      PTERODACTYL_KEY: ${{ secrets.PTERODACTYL_KEY }}
      PTERODACTYL_SERVER: "9822c231"
      PTERODACTYL_URL: ${{ secrets.PTERODACTYL_URL }}
    with:
      PROJECT_NAME: "holylib"
      BUILD_64x: "false"
      REALM: "sv"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "false"
      UPLOAD: "pterodactyl"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-7"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-3"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
      PTERODACTYL_RESTART_SLEEPTIME: "0"
      PTERODACTYL_RESTART: "true"
      BUILD_CACHE: "true"

  build_testingarea_64x:
    name: "Build 64x (Testing Area - 64x)"
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    secrets:
      PTERODACTYL_KEY: ${{ secrets.PTERODACTYL_KEY }}
      PTERODACTYL_SERVER: "4ef145c3"
      PTERODACTYL_URL: ${{ secrets.PTERODACTYL_URL }}
    with:
      PROJECT_NAME: "holylib"
      BUILD_64x: "true"
      BUILD_32x: "false"
      REALM: "sv"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "false"
      UPLOAD: "pterodactyl"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-7"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-3"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
      PTERODACTYL_RESTART_SLEEPTIME: "0"
      PTERODACTYL_RESTART: "true"
      BUILD_CACHE: "true"

  build_ghostinj:
    name: "Build GhostInj"
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_PATH: "ghostinj-dll/"
      PROJECT_NAME: "ghostinj"
      BUILD_64x: "true"
      LINUX_FILEEXTENTION: "dll"
      BUILD_WINDOWS: "false"
      USE_PREFIX: "false"
      ARTIFACT_EXPIRE: "1"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-7"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-3"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
      BUILD_CACHE: "true"

  setup_32x_artifacts:
    name: "Setup 32x Artifact"
    needs: [build_plugin_linux, build_ghostinj]
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v4
        name: "Checkout required files"
        with:
          sparse-checkout: |
            holylib.vdf
            gluatests

      - uses: actions/download-artifact@v4
        name: "Download 32x plugin"
        with:
          name: "gmsv_holylib_linux.so"

      - uses: actions/download-artifact@v4
        name: "Download 32x ghostinj"
        with:
          name: "ghostinj.dll"

      - name: "Create structure"
        run: |
          mkdir -p garrysmod/lua/bin
          mv gmsv_holylib_linux.so garrysmod/lua/bin/

          mkdir -p garrysmod/addons
          mv holylib.vdf garrysmod/addons
          mv gluatests garrysmod/addons

          tar -czf gluatest.tar.gz ghostinj.dll garrysmod/
          tar -czf gluatest_no_ghostinj.tar.gz garrysmod/

      - uses: actions/upload-artifact@v4
        name: "Upload tar"
        with:
          name: gluatest_32x
          path: gluatest.tar.gz
          compression-level: 9
          retention-days: 1

      - uses: actions/upload-artifact@v4
        name: "Upload tar"
        with:
          name: gluatest_no_ghostinj_32x
          path: gluatest_no_ghostinj.tar.gz
          compression-level: 9
          retention-days: 1

  setup_64x_artifacts:
    name: "Setup 64x Artifact"
    needs: [build_plugin_linux, build_ghostinj]
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v4
        name: "Checkout required files"
        with:
          sparse-checkout: |
            holylib_64.vdf
            gluatests

      - uses: actions/download-artifact@v4
        name: "Download 64x plugin"
        with:
          name: "gmsv_holylib_linux64.so (64x)"

      - uses: actions/download-artifact@v4
        name: "Download 64x ghostinj"
        with:
          name: "ghostinj.dll (64x)"

      - name: "Create structure"
        run: |
          mkdir -p garrysmod/lua/bin
          mv gmsv_holylib_linux64.so garrysmod/lua/bin/

          mkdir -p garrysmod/addons
          mv holylib_64.vdf garrysmod/addons
          mv gluatests garrysmod/addons

          tar -czf gluatest.tar.gz ghostinj.dll garrysmod/
          tar -czf gluatest_no_ghostinj.tar.gz garrysmod/

      - uses: actions/upload-artifact@v4
        name: "Upload tar"
        with:
          name: gluatest_64x
          path: gluatest.tar.gz
          compression-level: 9
          retention-days: 1

      - uses: actions/upload-artifact@v4
        name: "Upload tar"
        with:
          name: gluatest_no_ghostinj_64x
          path: gluatest_no_ghostinj.tar.gz
          compression-level: 9
          retention-days: 1

  test_32bit:
    name: "Test 32x branches"
    needs: setup_32x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        branch:
          - live
          - dev
          - prerelease
    with:
      extra-startup-args: "-usegh"
      download-artifact: "gluatest_32x"
      no-checkout: "true"

  test_32bit_noghostinj:
    name: "Test 32x branches (No GhostInj)"
    needs: setup_32x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        branch:
          - live
          - dev
          - prerelease
    with:
      download-artifact: "gluatest_no_ghostinj_32x"
      no-checkout: "true"

  test_64bit:
    name: "Test x86-64 branch"
    needs: setup_64x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      branch: x86-64
      extra-startup-args: "-usegh"
      download-artifact: "gluatest_64x"
      no-checkout: "true"

  test_64bit_noghostinj:
    name: "Test x86-64 branch (No GhostInj)"
    needs: setup_64x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      branch: x86-64
      download-artifact: "gluatest_no_ghostinj_64x"
      no-checkout: "true"

  test_32x_holylua:
    name: "Test 32x branches (HolyLua)"
    needs: setup_32x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        branch:
          - live
          - dev
          - prerelease
    with:
      extra-startup-args: "-usegh -holylib_lua +holylib_module_debug 0"
      download-artifact: "gluatest_32x"
      no-checkout: "true"

  test_32x_holylua_noghostinj:
    name: "Test 32x branches (HolyLua, No GhostInj)"
    needs: setup_32x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        branch:
          - live
          - dev
          - prerelease
    with:
      extra-startup-args: "-holylib_lua +holylib_module_debug 0"
      download-artifact: "gluatest_no_ghostinj_32x"
      no-checkout: "true"

  test_64bit_holylua:
    name: "Test x86-64 branch (HolyLua)"
    needs: setup_64x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      branch: x86-64
      extra-startup-args: "-usegh -holylib_lua +holylib_module_debug 0"
      download-artifact: "gluatest_64x"
      no-checkout: "true"

  test_64bit_holylua_noghostinj:
    name: "Test x86-64 branch (HolyLua, No GhostInj)"
    needs: setup_64x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      branch: x86-64
      extra-startup-args: "-holylib_lua +holylib_module_debug 0"
      download-artifact: "gluatest_no_ghostinj_64x"
      no-checkout: "true"

  # We run gmod_tests repo to ensure that we didn't break any gmod functions unknowingly.
  setup_gmod_tests_32x_artifacts:
    name: "Setup gmod_tests 32x Artifact"
    needs: [setup_32x_artifacts]
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v4
        name: "Checkout gmod_tests repo"
        with:
          sparse-checkout: lua
          repository: 'CFC-Servers/gmod_tests'
          path: 'gmod_tests'

      - uses: actions/download-artifact@v4
        name: "Download 32x artifact"
        with:
          name: "gluatest_32x"

      - name: "Setup structure"
        run: |
          mkdir -p garrysmod/lua/bin
          mkdir -p garrysmod/addons

          tar -xzf gluatest.tar.gz

          mv gmod_tests garrysmod/addons
          mv ghostinj.dll ghostinj2.dll
          rm -rf garrysmod/addons/gluatests

          tar -czf gmod_tests.tar.gz ghostinj2.dll garrysmod/
          tar -czf gmod_tests_no_ghostinj.tar.gz garrysmod/

      - uses: actions/upload-artifact@v4
        name: "Upload tar"
        with:
          name: gmod_tests_32x
          path: gmod_tests.tar.gz
          compression-level: 9
          retention-days: 1

      - uses: actions/upload-artifact@v4
        name: "Upload tar"
        with:
          name: gmod_tests_no_ghostinj_32x
          path: gmod_tests_no_ghostinj.tar.gz
          compression-level: 9
          retention-days: 1

  setup_gmod_tests_64x_artifacts:
    name: "Setup gmod_tests 64x Artifact"
    needs: [setup_64x_artifacts]
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v4
        name: "Checkout gmod_tests repo"
        with:
          sparse-checkout: lua
          repository: 'CFC-Servers/gmod_tests'
          path: 'gmod_tests'

      - uses: actions/download-artifact@v4
        name: "Download 64x artifact"
        with:
          name: "gluatest_64x"

      - name: "Setup structure"
        run: |
          mkdir -p garrysmod/lua/bin
          mkdir -p garrysmod/addons

          tar -xzf gluatest.tar.gz

          mv gmod_tests garrysmod/addons
          mv ghostinj.dll ghostinj2.dll
          rm -rf garrysmod/addons/gluatests

          tar -czf gmod_tests.tar.gz ghostinj2.dll garrysmod/
          tar -czf gmod_tests_no_ghostinj.tar.gz garrysmod/

      - uses: actions/upload-artifact@v4
        name: "Upload tar"
        with:
          name: gmod_tests_64x
          path: gmod_tests.tar.gz
          compression-level: 9
          retention-days: 1

      - uses: actions/upload-artifact@v4
        name: "Upload tar"
        with:
          name: gmod_tests_no_ghostinj_64x
          path: gmod_tests_no_ghostinj.tar.gz
          compression-level: 9
          retention-days: 1

  test_gmod_tests_32bit:
    name: "Test 32x branches (gmod_tests)"
    needs: setup_gmod_tests_32x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        branch:
          - live
          - dev
          - prerelease
        artifact:
          - gmod_tests_32x
          - gmod_tests_no_ghostinj_32x
    with:
      extra-startup-args: "-usegh -maxplayers 64"
      download-artifact: ${{ matrix.artifact }}
      no-checkout: "true"
      additional-setup: "wget -q https://github.com/RaphaelIT7/gmod-holytest/releases/latest/download/linux32.tar.gz -O gluatest/docker/_gluatest_artifacts/linux32.tar.gz"
      collection: 3460542547
      map: gm_glua_tests

  test_gmod_tests_32bit_luajit:
    name: "Test 32x branches (gmod_tests + LuaJIT module)"
    needs: setup_gmod_tests_32x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        branch:
          - live
          - dev
          - prerelease
        artifact:
          - gmod_tests_32x
          - gmod_tests_no_ghostinj_32x
    with:
      extra-startup-args: "-usegh -maxplayers 64 -holylib_enable_luajit 1"
      download-artifact: ${{ matrix.artifact }}
      no-checkout: "true"
      additional-setup: "wget -q https://github.com/RaphaelIT7/gmod-holytest/releases/latest/download/linux32.tar.gz -O gluatest/docker/_gluatest_artifacts/linux32.tar.gz"
      collection: 3460542547
      map: gm_glua_tests

  test_gmod_tests_64bit:
    name: "Test x86-64 branch (gmod_tests)"
    needs: setup_gmod_tests_64x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        artifact:
          - gmod_tests_64x
          - gmod_tests_no_ghostinj_64x
    with:
      branch: x86-64
      extra-startup-args: "-usegh -maxplayers 64"
      download-artifact: ${{ matrix.artifact }}
      no-checkout: "true"
      additional-setup: "wget -q https://github.com/RaphaelIT7/gmod-holytest/releases/latest/download/linux64.tar.gz -O gluatest/docker/_gluatest_artifacts/linux64.tar.gz"
      collection: 3460542547
      map: gm_glua_tests

  test_gmod_tests_32bit_with_ivpreplacement:
    name: "Test 32x branches (gmod_tests & VPhysics replacement)"
    needs: setup_gmod_tests_32x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        branch:
          - live
          - dev
          - prerelease
        artifact:
          - gmod_tests_32x
          - gmod_tests_no_ghostinj_32x
    with:
      extra-startup-args: "-usegh -maxplayers 64 -holylib_replaceivp"
      download-artifact: ${{ matrix.artifact }}
      no-checkout: "true"
      additional-setup: "wget -q https://github.com/RaphaelIT7/gmod-holytest/releases/latest/download/linux32.tar.gz -O gluatest/docker/_gluatest_artifacts/linux32.tar.gz"
      collection: 3460542547
      map: gm_glua_tests

  test_gmod_tests_64bit_with_ivpreplacement:
    name: "Test x86-64 branch (gmod_tests & VPhysics replacement)"
    needs: setup_gmod_tests_64x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      matrix:
        artifact:
          - gmod_tests_64x
          - gmod_tests_no_ghostinj_64x
    with:
      branch: x86-64
      extra-startup-args: "-usegh -maxplayers 64 -holylib_replaceivp"
      download-artifact: ${{ matrix.artifact }}
      no-checkout: "true"
      additional-setup: "wget -q https://github.com/RaphaelIT7/gmod-holytest/releases/latest/download/linux64.tar.gz -O gluatest/docker/_gluatest_artifacts/linux64.tar.gz"
      collection: 3460542547
      map: gm_glua_tests

  test_32bit_find_crash:
    if: false # always() Enable it if a unknown crash is happening. We'll test every single module.
    name: "Find the crash cause"
    needs: setup_32x_artifacts
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    strategy:
      fail-fast: false
      matrix:
        module: 
          - holylib
          - gameevent
          - serverplugin
          - sourcetv
          - threadpoolfix
          - stringtable
          - precachefix
          - pvs
          - surffix
          - filesystem
          - util
          - concommand
          - vprof
          - cvars
          - bitbuf
          - networking
          - steamworks
          - pas
          - bass
          - systimer
          - voicechat
          - physenv
          - net
          - entitylist
          - httpserver
          - gameserver
          - soundscape
          - luajit
    with:
      branch: dev
      extra-startup-args: "-usegh -holylib_startdisabled -holylib_enable_${{ matrix.module }} 1"
      download-artifact: "gluatest_32x"
      no-checkout: "true"